version: "3"

services:
  fuel_stats_db:
    container_name: fuel_stats_db
    image: mysql
    volumes:
      - /var/lib/docker/volumes/fuel_stats_volume/_data
    ports:
      - "3307:3306"
    env_file:
      - env_db.txt

  fuel_stats_app:
    build: .
    container_name: fuel_stats_app
    restart: always
    image: fuel_stats_img
    depends_on:
      - fuel_stats_db
    ports:
       - "8081:8080"
    env_file:
      - env.txt